# Generated by Django 5.2 on 2025-05-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoLotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='lotes/')),
                ('extencion', models.CharField(max_length=20)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
