# Generated by Django 5.2 on 2025-05-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArchivoLotes',
            new_name='ArchivoLote',
        ),
        migrations.RenameField(
            model_name='archivolote',
            old_name='extencion',
            new_name='extension',
        ),
    ]
