# Generated by Django 5.2 on 2025-05-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_rename_archivolotes_archivolote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivolote',
            name='lote',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
