# Generated by Django 5.2 on 2025-05-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_lote_remove_archivolote_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivolote',
            name='nombre',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lote',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
