# Generated by Django 5.2 on 2025-05-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_archivolote_nombre_alter_lote_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivolote',
            name='tipo',
            field=models.CharField(choices=[('cosecha', 'Cosecha'), ('suelo', 'Análisis de Suelo')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
